# Generated by Django 6.0.3 on 2026-03-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DengueMonthlyDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month (YYYY-MM-01).')),
                ('municipality_code', models.CharField(max_length=20, null=True)),
                ('health_region_code', models.CharField(max_length=20, null=True)),
                ('temp_mean', models.FloatField(null=True)),
                ('temp_max_mean', models.FloatField(null=True)),
                ('temp_min_mean', models.FloatField(null=True)),
                ('humidity_mean', models.FloatField(null=True)),
                ('humidity_max_mean', models.FloatField(null=True)),
                ('humidity_min_mean', models.FloatField(null=True)),
                ('rain_sum', models.FloatField(null=True)),
                ('pressure_mean', models.FloatField(null=True)),
                ('wind_speed_mean', models.FloatField(null=True)),
                ('solar_radiation_sum', models.FloatField(null=True)),
                ('optimal_days', models.PositiveSmallIntegerField(null=True)),
                ('dengue_cases', models.PositiveIntegerField(null=True)),
                ('dengue_cases_next', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'dengue_monthly_dataset',
                'indexes': [models.Index(fields=['month'], name='idx_dengue_monthly_month'), models.Index(fields=['municipality_code', 'month'], name='idx_dengue_monthly_city_month')],
                'constraints': [models.UniqueConstraint(fields=('month', 'municipality_code', 'health_region_code'), name='uniq_dengue_monthly_dataset_month_city_region')],
            },
        ),
    ]
