# Generated by Django 6.0.3 on 2026-03-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbovirus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DengueWeeklyDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('epidemiological_year', models.PositiveSmallIntegerField(null=True)),
                ('epidemiological_week', models.PositiveSmallIntegerField(null=True)),
                ('municipality_code', models.CharField(max_length=20, null=True)),
                ('health_region_code', models.CharField(max_length=20, null=True)),
                ('temp_mean', models.FloatField(null=True)),
                ('temp_max_mean', models.FloatField(null=True)),
                ('temp_min_mean', models.FloatField(null=True)),
                ('humidity_mean', models.FloatField(null=True)),
                ('humidity_max_mean', models.FloatField(null=True)),
                ('humidity_min_mean', models.FloatField(null=True)),
                ('rain_sum', models.FloatField(null=True)),
                ('pressure_mean', models.FloatField(null=True)),
                ('wind_speed_mean', models.FloatField(null=True)),
                ('solar_radiation_sum', models.FloatField(null=True)),
                ('optimal_days', models.PositiveSmallIntegerField(null=True)),
                ('dengue_cases', models.PositiveIntegerField(null=True)),
                ('dengue_cases_next', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'dengue_weekly_dataset',
                'indexes': [models.Index(fields=['week_start'], name='idx_dengue_weekly_week_start'), models.Index(fields=['epidemiological_year', 'epidemiological_week'], name='idx_dengue_weekly_epi_year_week'), models.Index(fields=['municipality_code', 'week_start'], name='idx_dengue_weekly_city_week')],
                'constraints': [models.UniqueConstraint(fields=('week_start', 'municipality_code', 'health_region_code'), name='uniq_dengue_weekly_dataset_week_city_region')],
            },
        ),
    ]
