from django.db import models


class SinanNotification(models.Model):
    """
    Represents a SINAN (Brazilian Notifiable Diseases Information System) case notification.

    Fields meaning:
    - id: Unique identifier of the notification (auto-generated by Django).
    - notification_date: Date when the condition/case was notified.
    - notification_epidemiological_week: Epidemiological week of the notification.
    - notification_year: Year of the notification.
    - disease_code: Code of the reported condition/disease.
    - notification_municipality_code: Municipality code where the notification was registered.
    - health_region_code: Health region code responsible for the notification (regional authority).
    - reporting_health_unit_code: Code of the health unit that reported the notification.
    - sex: Patient sex.
    - race_color: Patient self-declared race/color.
    - education_level: Patient education level.
    - residence_municipality_code: Municipality code of the patient's residence.
    - residence_health_region_code: Health region code of the patient's residence.
    - case_outcome: Case outcome/evolution (e.g., cured, death, under follow-up).
    - age_years: Patient age in years at the time of notification.
    """

    notification_date = models.DateField()

    notification_epidemiological_week = models.PositiveSmallIntegerField()

    notification_year = models.PositiveSmallIntegerField()

    disease_code = models.CharField(
        max_length=50
    )

    notification_municipality_code = models.CharField(
        max_length=20
    )

    health_region_code = models.CharField(
        max_length=20
    )

    reporting_health_unit_code = models.CharField(
        max_length=20
    )

    sex = models.CharField(
        max_length=20
    )

    race_color = models.CharField(
        max_length=30
    )

    education_level = models.CharField(
        max_length=50
    )

    residence_municipality_code = models.CharField(
        max_length=20
    )

    residence_health_region_code = models.CharField(
        max_length=20
    )

    case_outcome = models.CharField(
        max_length=50
    )

    age_years = models.PositiveSmallIntegerField()

    class Meta:
        db_table = "sinan_notification"
