# Generated by Django 6.0.3 on 2026-03-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InmetWeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(null=True)),
                ('observation_time_utc', models.TimeField(null=True)),
                ('air_temperature_instant_celsius', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('air_temperature_max_celsius', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('air_temperature_min_celsius', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('relative_humidity_instant_percent', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('relative_humidity_max_percent', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('relative_humidity_min_percent', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('dew_point_temperature_instant_celsius', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('dew_point_temperature_max_celsius', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('dew_point_temperature_min_celsius', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('atmospheric_pressure_instant_hpa', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('atmospheric_pressure_max_hpa', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('atmospheric_pressure_min_hpa', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('wind_speed_mean_meters_per_second', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('wind_direction_degrees', models.PositiveSmallIntegerField(null=True)),
                ('wind_gust_max_meters_per_second', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('global_solar_radiation_kj_per_square_meter', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('precipitation_accumulated_millimeters', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'inmet_weather_observation',
            },
        ),
    ]
