# Generated by Django 6.0.3 on 2026-03-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAdmission',
            fields=[
                ('record_identifier', models.BigAutoField(primary_key=True, serialize=False)),
                ('processing_competence_year', models.PositiveSmallIntegerField()),
                ('processing_competence_month', models.PositiveSmallIntegerField()),
                ('admission_state_code', models.CharField(max_length=2)),
                ('bed_or_admission_specialty_code', models.CharField(max_length=3)),
                ('health_facility_registry_code', models.CharField(max_length=7)),
                ('patient_residence_municipality_code', models.CharField(max_length=6)),
                ('admission_municipality_code', models.CharField(max_length=6)),
                ('patient_birth_date', models.DateField()),
                ('patient_sex', models.CharField(max_length=1)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('primary_diagnosis_icd10_code', models.CharField(max_length=4)),
                ('death_during_admission', models.BooleanField(default=False)),
                ('intensive_care_total_days', models.PositiveSmallIntegerField(default=0)),
                ('admission_type', models.CharField(max_length=2)),
                ('total_amount_paid_brl', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
