# Generated by Django 6.0.3 on 2026-03-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaladmission',
            name='admission_municipality_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitaladmission',
            name='admission_state_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitaladmission',
            name='admission_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hospitaladmission',
            name='bed_or_admission_specialty_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitaladmission',
            name='health_facility_registry_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitaladmission',
            name='patient_residence_municipality_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitaladmission',
            name='patient_sex',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitaladmission',
            name='primary_diagnosis_icd10_code',
            field=models.CharField(max_length=10),
        ),
    ]
