# Generated by Django 6.0.3 on 2026-03-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0002_alter_hospitaladmission_admission_municipality_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaladmission',
            name='bed_or_admission_specialty_code',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='hospitaladmission',
            name='health_facility_registry_code',
            field=models.CharField(max_length=255),
        ),
    ]
