# Generated by Django 6.0.3 on 2026-03-06 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0003_alter_hospitaladmission_bed_or_admission_specialty_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalOccupancyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(db_index=True, max_length=255)),
                ('week_start', models.DateField(db_index=True)),
                ('real_total', models.IntegerField(blank=True, null=True)),
                ('estimated_total', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'hospital_occupancy_predictions',
                'indexes': [models.Index(fields=['week_start', 'hospital'], name='idx_current_week_hospital')],
                'constraints': [models.UniqueConstraint(fields=('hospital', 'week_start'), name='uq_hospital_week_start_current')],
            },
        ),
        migrations.CreateModel(
            name='HospitalOccupancyPredictionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('train_from', models.IntegerField(blank=True, null=True)),
                ('train_to', models.IntegerField(blank=True, null=True)),
                ('test_year', models.IntegerField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, default='', max_length=512)),
                ('csv_path', models.CharField(blank=True, default='', max_length=512)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('rows_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospital_occupancy_prediction_runs',
                'indexes': [models.Index(fields=['run_at'], name='idx_pred_run_at')],
            },
        ),
        migrations.CreateModel(
            name='HospitalOccupancyPredictionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(db_index=True, max_length=255)),
                ('week_start', models.DateField(db_index=True)),
                ('real_total', models.IntegerField(blank=True, null=True)),
                ('estimated_total', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='sih.hospitaloccupancypredictionrun')),
            ],
            options={
                'db_table': 'hospital_occupancy_predictions_audit',
                'indexes': [models.Index(fields=['run', 'hospital', 'week_start'], name='idx_audit_run_hosp_week'), models.Index(fields=['hospital', 'week_start'], name='idx_audit_hosp_week')],
            },
        ),
    ]
