# Generated by Django 6.0.3 on 2026-03-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0004_hospitaloccupancyprediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaloccupancyprediction',
            name='estimated_avg_length_of_stay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaloccupancyprediction',
            name='real_avg_length_of_stay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaloccupancypredictionaudit',
            name='estimated_avg_length_of_stay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaloccupancypredictionaudit',
            name='real_avg_length_of_stay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaloccupancypredictionrun',
            name='los_mae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaloccupancypredictionrun',
            name='los_r2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitaloccupancypredictionrun',
            name='los_rmse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
