# Generated by Django 6.0.3 on 2026-03-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinanNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateField()),
                ('notification_epidemiological_week', models.PositiveSmallIntegerField()),
                ('notification_year', models.PositiveSmallIntegerField()),
                ('disease_code', models.CharField(max_length=50)),
                ('notification_municipality_code', models.CharField(max_length=20)),
                ('health_region_code', models.CharField(max_length=20)),
                ('reporting_health_unit_code', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('race_color', models.CharField(max_length=30)),
                ('education_level', models.CharField(max_length=50)),
                ('residence_municipality_code', models.CharField(max_length=20)),
                ('residence_health_region_code', models.CharField(max_length=20)),
                ('case_outcome', models.CharField(max_length=50)),
                ('age_years', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'sinan_notification',
            },
        ),
    ]
