# Generated by Django 6.0.3 on 2026-03-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinannotification',
            name='age_years',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='case_outcome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='disease_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='education_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='health_region_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='notification_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='notification_epidemiological_week',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='notification_municipality_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='notification_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='race_color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='reporting_health_unit_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='residence_health_region_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='residence_municipality_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sinannotification',
            name='sex',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
